// <auto-generated />
using System;
using API_TFCAppDavid.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_TFCAppDavid.Migrations
{
    [DbContext(typeof(ASPContext))]
    [Migration("20260503154322_InitialHelpSphere")]
    partial class InitialHelpSphere
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_TFCAppDavid.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            IdCategoria = 1,
                            Descripcion = "Ayuda, acompañamiento y recados para personas mayores",
                            Nombre = "Personas mayores"
                        },
                        new
                        {
                            IdCategoria = 2,
                            Descripcion = "Paseo y cuidado puntual de animales domésticos",
                            Nombre = "Mascotas"
                        },
                        new
                        {
                            IdCategoria = 3,
                            Descripcion = "Ayuda con móviles, ordenadores y programas",
                            Nombre = "Informática"
                        },
                        new
                        {
                            IdCategoria = 4,
                            Descripcion = "Apoyo educativo o formación básica",
                            Nombre = "Clases"
                        },
                        new
                        {
                            IdCategoria = 5,
                            Descripcion = "Compras, gestiones y pequeñas tareas cotidianas",
                            Nombre = "Recados"
                        },
                        new
                        {
                            IdCategoria = 6,
                            Descripcion = "Pequeñas reparaciones domésticas",
                            Nombre = "Reparaciones"
                        });
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.MovimientoPuntos", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdPublicacion")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdMovimiento");

                    b.HasIndex("IdPublicacion");

                    b.HasIndex("IdUsuario");

                    b.ToTable("MovimientosPuntos");

                    b.HasData(
                        new
                        {
                            IdMovimiento = 1,
                            Cantidad = 100,
                            Descripcion = "Saldo inicial de prueba para administrador.",
                            FechaMovimiento = new DateTime(2026, 5, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdUsuario = 1,
                            TipoMovimiento = "AJUSTE"
                        },
                        new
                        {
                            IdMovimiento = 2,
                            Cantidad = 20,
                            Descripcion = "Puntos obtenidos por realizar un recado.",
                            FechaMovimiento = new DateTime(2026, 5, 4, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            IdPublicacion = 3,
                            IdUsuario = 2,
                            TipoMovimiento = "GANANCIA"
                        },
                        new
                        {
                            IdMovimiento = 3,
                            Cantidad = -20,
                            Descripcion = "Puntos gastados por solicitar ayuda en un recado.",
                            FechaMovimiento = new DateTime(2026, 5, 4, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            IdPublicacion = 3,
                            IdUsuario = 3,
                            TipoMovimiento = "GASTO"
                        });
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Publicacion", b =>
                {
                    b.Property<int>("IdPublicacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPublicacion"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaServicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioCreador")
                        .HasColumnType("int");

                    b.Property<int>("PuntosEstimados")
                        .HasColumnType("int");

                    b.Property<string>("TipoPublicacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdPublicacion");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdUsuarioCreador");

                    b.ToTable("Publicaciones");

                    b.HasData(
                        new
                        {
                            IdPublicacion = 1,
                            Descripcion = "Necesito ayuda para instalar programas básicos y configurar el correo electrónico.",
                            Estado = "ABIERTA",
                            FechaCreacion = new DateTime(2026, 5, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaServicio = new DateTime(2026, 5, 10, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 3,
                            IdUsuarioCreador = 3,
                            PuntosEstimados = 25,
                            TipoPublicacion = "SOLICITUD",
                            Titulo = "Ayuda para configurar un ordenador portátil",
                            Zona = "Madrid"
                        },
                        new
                        {
                            IdPublicacion = 2,
                            Descripcion = "Ofrezco ayuda para pasear perros por la zona durante las tardes.",
                            Estado = "ABIERTA",
                            FechaCreacion = new DateTime(2026, 5, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            FechaServicio = new DateTime(2026, 5, 8, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 2,
                            IdUsuarioCreador = 2,
                            PuntosEstimados = 15,
                            TipoPublicacion = "OFERTA",
                            Titulo = "Paseo de mascotas por la tarde",
                            Zona = "Madrid"
                        },
                        new
                        {
                            IdPublicacion = 3,
                            Descripcion = "Necesito ayuda para hacer una compra pequeña en el supermercado.",
                            Estado = "ABIERTA",
                            FechaCreacion = new DateTime(2026, 5, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaServicio = new DateTime(2026, 5, 6, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            IdCategoria = 5,
                            IdUsuarioCreador = 3,
                            PuntosEstimados = 20,
                            TipoPublicacion = "SOLICITUD",
                            Titulo = "Recado para compra semanal",
                            Zona = "Getafe"
                        });
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            IdRol = 1,
                            NombreRol = "Administrador"
                        },
                        new
                        {
                            IdRol = 2,
                            NombreRol = "Usuario"
                        });
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.SolicitudParticipacion", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSolicitud"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPublicacion")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioSolicitante")
                        .HasColumnType("int");

                    b.Property<string>("Mensaje")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdUsuarioSolicitante");

                    b.HasIndex("IdPublicacion", "IdUsuarioSolicitante")
                        .IsUnique();

                    b.ToTable("SolicitudesParticipacion");

                    b.HasData(
                        new
                        {
                            IdSolicitud = 1,
                            Estado = "PENDIENTE",
                            FechaSolicitud = new DateTime(2026, 5, 3, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            IdPublicacion = 1,
                            IdUsuarioSolicitante = 2,
                            Mensaje = "Hola, puedo ayudarte con la configuración del ordenador."
                        },
                        new
                        {
                            IdSolicitud = 2,
                            Estado = "ACEPTADA",
                            FechaSolicitud = new DateTime(2026, 5, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            IdPublicacion = 3,
                            IdUsuarioSolicitante = 2,
                            Mensaje = "Puedo hacer el recado esta semana."
                        });
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Apellidos")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirebaseUid")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FotoPerfil")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ReputacionMedia")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<int>("SaldoPuntos")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zona")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            IdUsuario = 1,
                            Activo = true,
                            Apellidos = "Bermudez",
                            Descripcion = "Usuario administrador inicial para pruebas.",
                            Email = "admin@helpsphere.local",
                            FechaRegistro = new DateTime(2026, 5, 3, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            FirebaseUid = "firebase-admin-demo-001",
                            IdRol = 1,
                            Nombre = "David",
                            ReputacionMedia = 5.00m,
                            SaldoPuntos = 100,
                            Telefono = "600111222",
                            Zona = "Cordoba"
                        },
                        new
                        {
                            IdUsuario = 2,
                            Activo = true,
                            Apellidos = "García",
                            Descripcion = "Usuaria de prueba interesada en ofrecer ayuda.",
                            Email = "laura@helpsphere.local",
                            FechaRegistro = new DateTime(2026, 5, 3, 10, 15, 0, 0, DateTimeKind.Unspecified),
                            FirebaseUid = "firebase-user-demo-002",
                            IdRol = 2,
                            Nombre = "Laura",
                            ReputacionMedia = 4.50m,
                            SaldoPuntos = 50,
                            Telefono = "600222333",
                            Zona = "Cordoba"
                        },
                        new
                        {
                            IdUsuario = 3,
                            Activo = true,
                            Apellidos = "Sánchez",
                            Descripcion = "Usuario de prueba que solicita ayuda puntual.",
                            Email = "miguel@helpsphere.local",
                            FechaRegistro = new DateTime(2026, 5, 3, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            FirebaseUid = "firebase-user-demo-003",
                            IdRol = 2,
                            Nombre = "Miguel",
                            ReputacionMedia = 0.00m,
                            SaldoPuntos = 30,
                            Telefono = "600333444",
                            Zona = "Cordoba"
                        });
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Valoracion", b =>
                {
                    b.Property<int>("IdValoracion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdValoracion"));

                    b.Property<string>("Comentario")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaValoracion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPublicacion")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioEmisor")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioReceptor")
                        .HasColumnType("int");

                    b.Property<int>("Puntuacion")
                        .HasColumnType("int");

                    b.HasKey("IdValoracion");

                    b.HasIndex("IdPublicacion");

                    b.HasIndex("IdUsuarioEmisor");

                    b.HasIndex("IdUsuarioReceptor");

                    b.ToTable("Valoraciones");

                    b.HasData(
                        new
                        {
                            IdValoracion = 1,
                            Comentario = "Muy amable y puntual.",
                            FechaValoracion = new DateTime(2026, 5, 4, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            IdPublicacion = 3,
                            IdUsuarioEmisor = 3,
                            IdUsuarioReceptor = 2,
                            Puntuacion = 5
                        });
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.MovimientoPuntos", b =>
                {
                    b.HasOne("API_TFCAppDavid.Models.Publicacion", "Publicacion")
                        .WithMany("MovimientosPuntos")
                        .HasForeignKey("IdPublicacion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API_TFCAppDavid.Models.Usuario", "Usuario")
                        .WithMany("MovimientoPuntos")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Publicacion", b =>
                {
                    b.HasOne("API_TFCAppDavid.Models.Categoria", "Categoria")
                        .WithMany("Publicaciones")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_TFCAppDavid.Models.Usuario", "UsuarioCreador")
                        .WithMany("PublicacionesCreadas")
                        .HasForeignKey("IdUsuarioCreador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("UsuarioCreador");
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.SolicitudParticipacion", b =>
                {
                    b.HasOne("API_TFCAppDavid.Models.Publicacion", "Publicacion")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdPublicacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_TFCAppDavid.Models.Usuario", "UsuarioSolicitante")
                        .WithMany("SolicitudesRealizadas")
                        .HasForeignKey("IdUsuarioSolicitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Usuario", b =>
                {
                    b.HasOne("API_TFCAppDavid.Models.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Valoracion", b =>
                {
                    b.HasOne("API_TFCAppDavid.Models.Publicacion", "Publicacion")
                        .WithMany("Valoraciones")
                        .HasForeignKey("IdPublicacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_TFCAppDavid.Models.Usuario", "UsuarioEmisor")
                        .WithMany("ValoracionesEmitidas")
                        .HasForeignKey("IdUsuarioEmisor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_TFCAppDavid.Models.Usuario", "UsuarioReceptor")
                        .WithMany("ValoracionesRecibidas")
                        .HasForeignKey("IdUsuarioReceptor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Publicacion");

                    b.Navigation("UsuarioEmisor");

                    b.Navigation("UsuarioReceptor");
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Categoria", b =>
                {
                    b.Navigation("Publicaciones");
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Publicacion", b =>
                {
                    b.Navigation("MovimientosPuntos");

                    b.Navigation("Solicitudes");

                    b.Navigation("Valoraciones");
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("API_TFCAppDavid.Models.Usuario", b =>
                {
                    b.Navigation("MovimientoPuntos");

                    b.Navigation("PublicacionesCreadas");

                    b.Navigation("SolicitudesRealizadas");

                    b.Navigation("ValoracionesEmitidas");

                    b.Navigation("ValoracionesRecibidas");
                });
#pragma warning restore 612, 618
        }
    }
}
